### ISSUE TITLE
Create an external reset button for the Jetson Nano

### ISSUE THREAD

**Issue by cmcgowan27** [RockRaidersInc/Electrical#65]
For reasons beyond my understanding, we need to power cycle the Jetson fairly regularly. Having a button outside the chassis would make this way easier.

The button should go in series with the power supply, and cut off the power when pressed.The circuit needs to be able to switch 2A.

Design Suggestion:
Since buttons usually have the opposite behavior, you might need to put a transistor in series with the power supply and use a pull up resistor to keep it on. Then just have the button hold the gate of the transistor at ground when pressed.

**Comment by cmcgowan27** [comment]
I just got a nice rocker switch that we could use for this

**Comment by YoshikoJanai** [comment]
Note for the switch: Sides are isolated from each other, when looking at the switch from the sides the center contact is connected to the contact on the protruding part of the switch.

**Comment by YoshikoJanai** [comment]
Switch spliced into power line for Jetson. Switch will eventually be labeled. Top depressed = On, Bottom depressed = Off
